SP500_MAP = [{'symbol': 'GM', 'asset_type': 'cash_equity'}, {'symbol': 'AXON', 'asset_type': 'cash_equity'},
              {'symbol': 'GLW', 'asset_type': 'cash_equity'}, {'symbol': 'LRCX', 'asset_type': 'cash_equity'},
              {'symbol': 'HOLX', 'asset_type': 'cash_equity'}, {'symbol': 'HPE', 'asset_type': 'cash_equity'},
              {'symbol': 'HRL', 'asset_type': 'cash_equity'}, {'symbol': 'HSIC', 'asset_type': 'cash_equity'},
              {'symbol': 'HSY', 'asset_type': 'cash_equity'}, {'symbol': 'LYB', 'asset_type': 'cash_equity'},
              {'symbol': 'GILD', 'asset_type': 'cash_equity'}, {'symbol': 'ICE', 'asset_type': 'cash_equity'},
              {'symbol': 'IPG', 'asset_type': 'cash_equity'}, {'symbol': 'LYV', 'asset_type': 'cash_equity'},
              {'symbol': 'IDXX', 'asset_type': 'cash_equity'}, {'symbol': 'INVH', 'asset_type': 'cash_equity'},
              {'symbol': 'DUK', 'asset_type': 'cash_equity'}, {'symbol': 'ABT', 'asset_type': 'cash_equity'},
              {'symbol': 'INTC', 'asset_type': 'cash_equity'}, {'symbol': 'YUM', 'asset_type': 'cash_equity'},
              {'symbol': 'MCD', 'asset_type': 'cash_equity'}, {'symbol': 'MET', 'asset_type': 'cash_equity'},
              {'symbol': 'AIZ', 'asset_type': 'cash_equity'}, {'symbol': 'MSFT', 'asset_type': 'cash_equity'},
              {'symbol': 'MTB', 'asset_type': 'cash_equity'}, {'symbol': 'GIS', 'asset_type': 'cash_equity'},
              {'symbol': 'BRO', 'asset_type': 'cash_equity'}, {'symbol': 'INCY', 'asset_type': 'cash_equity'},
              {'symbol': 'CMI', 'asset_type': 'cash_equity'}, {'symbol': 'GEV', 'asset_type': 'cash_equity'},
              {'symbol': 'GEN', 'asset_type': 'cash_equity'}, {'symbol': 'NDAQ', 'asset_type': 'cash_equity'},
              {'symbol': 'NDSN', 'asset_type': 'cash_equity'}, {'symbol': 'GE', 'asset_type': 'cash_equity'},
              {'symbol': 'EXC', 'asset_type': 'cash_equity'}, {'symbol': 'BWA', 'asset_type': 'cash_equity'},
              {'symbol': 'IP', 'asset_type': 'cash_equity'}, {'symbol': 'IQV', 'asset_type': 'cash_equity'},
              {'symbol': 'IR', 'asset_type': 'cash_equity'}, {'symbol': 'GDDY', 'asset_type': 'cash_equity'},
              {'symbol': 'GD', 'asset_type': 'cash_equity'}, {'symbol': 'ED', 'asset_type': 'cash_equity'},
              {'symbol': 'ISRG', 'asset_type': 'cash_equity'}, {'symbol': 'IT', 'asset_type': 'cash_equity'},
              {'symbol': 'HST', 'asset_type': 'cash_equity'}, {'symbol': 'O', 'asset_type': 'cash_equity'},
              {'symbol': 'ON', 'asset_type': 'cash_equity'}, {'symbol': 'ORLY', 'asset_type': 'cash_equity'},
              {'symbol': 'PAYX', 'asset_type': 'cash_equity'}, {'symbol': 'PNW', 'asset_type': 'cash_equity'},
              {'symbol': 'PRU', 'asset_type': 'cash_equity'}, {'symbol': 'RCL', 'asset_type': 'cash_equity'},
              {'symbol': 'FTNT', 'asset_type': 'cash_equity'}, {'symbol': 'REGN', 'asset_type': 'cash_equity'},
              {'symbol': 'DD', 'asset_type': 'cash_equity'}, {'symbol': 'RVTY', 'asset_type': 'cash_equity'},
              {'symbol': 'HUM', 'asset_type': 'cash_equity'}, {'symbol': 'LMT', 'asset_type': 'cash_equity'},
              {'symbol': 'LOW', 'asset_type': 'cash_equity'}, {'symbol': 'SCHW', 'asset_type': 'cash_equity'},
              {'symbol': 'MSCI', 'asset_type': 'cash_equity'}, {'symbol': 'OMC', 'asset_type': 'cash_equity'},
              {'symbol': 'FSLR', 'asset_type': 'cash_equity'}, {'symbol': 'OXY', 'asset_type': 'cash_equity'},
              {'symbol': 'EMR', 'asset_type': 'cash_equity'}, {'symbol': 'HWM', 'asset_type': 'cash_equity'},
              {'symbol': 'SNA', 'asset_type': 'cash_equity'}, {'symbol': 'SOLV', 'asset_type': 'cash_equity'},
              {'symbol': 'SLB', 'asset_type': 'cash_equity'}, {'symbol': 'SPG', 'asset_type': 'cash_equity'},
              {'symbol': 'SPGI', 'asset_type': 'cash_equity'}, {'symbol': 'IFF', 'asset_type': 'cash_equity'},
              {'symbol': 'SYF', 'asset_type': 'cash_equity'}, {'symbol': 'IVZ', 'asset_type': 'cash_equity'},
              {'symbol': 'TAP', 'asset_type': 'cash_equity'}, {'symbol': 'TECH', 'asset_type': 'cash_equity'},
              {'symbol': 'TER', 'asset_type': 'cash_equity'}, {'symbol': 'TSCO', 'asset_type': 'cash_equity'},
              {'symbol': 'TSN', 'asset_type': 'cash_equity'}, {'symbol': 'ULTA', 'asset_type': 'cash_equity'},
              {'symbol': 'URI', 'asset_type': 'cash_equity'}, {'symbol': 'VRSK', 'asset_type': 'cash_equity'},
              {'symbol': 'VTRS', 'asset_type': 'cash_equity'}, {'symbol': 'VZ', 'asset_type': 'cash_equity'},
              {'symbol': 'WBA', 'asset_type': 'cash_equity'}, {'symbol': 'WBD', 'asset_type': 'cash_equity'},
              {'symbol': 'WDC', 'asset_type': 'cash_equity'}, {'symbol': 'WFC', 'asset_type': 'cash_equity'},
              {'symbol': 'WYNN', 'asset_type': 'cash_equity'}, {'symbol': 'XEL', 'asset_type': 'cash_equity'},
              {'symbol': 'ZBH', 'asset_type': 'cash_equity'}, {'symbol': 'ZBRA', 'asset_type': 'cash_equity'},
              {'symbol': 'EG', 'asset_type': 'cash_equity'}, {'symbol': 'J', 'asset_type': 'cash_equity'},
              {'symbol': 'JCI', 'asset_type': 'cash_equity'}, {'symbol': 'BR', 'asset_type': 'cash_equity'},
              {'symbol': 'AKAM', 'asset_type': 'cash_equity'}, {'symbol': 'JNJ', 'asset_type': 'cash_equity'},
              {'symbol': 'JNPR', 'asset_type': 'cash_equity'}, {'symbol': 'IEX', 'asset_type': 'cash_equity'},
              {'symbol': 'JPM', 'asset_type': 'cash_equity'}, {'symbol': 'AMP', 'asset_type': 'cash_equity'},
              {'symbol': 'DAY', 'asset_type': 'cash_equity'}, {'symbol': 'IRM', 'asset_type': 'cash_equity'},
              {'symbol': 'KEY', 'asset_type': 'cash_equity'}, {'symbol': 'KEYS', 'asset_type': 'cash_equity'},
              {'symbol': 'ITW', 'asset_type': 'cash_equity'}, {'symbol': 'KHC', 'asset_type': 'cash_equity'},
              {'symbol': 'KIM', 'asset_type': 'cash_equity'}, {'symbol': 'D', 'asset_type': 'cash_equity'},
              {'symbol': 'KKR', 'asset_type': 'cash_equity'}, {'symbol': 'KMB', 'asset_type': 'cash_equity'},
              {'symbol': 'KMI', 'asset_type': 'cash_equity'}, {'symbol': 'KMX', 'asset_type': 'cash_equity'},
              {'symbol': 'JBHT', 'asset_type': 'cash_equity'}, {'symbol': 'JBL', 'asset_type': 'cash_equity'},
              {'symbol': 'KR', 'asset_type': 'cash_equity'}, {'symbol': 'KVUE', 'asset_type': 'cash_equity'},
              {'symbol': 'FTV', 'asset_type': 'cash_equity'}, {'symbol': 'KDP', 'asset_type': 'cash_equity'},
              {'symbol': 'AJG', 'asset_type': 'cash_equity'}, {'symbol': 'FMC', 'asset_type': 'cash_equity'},
              {'symbol': 'KLAC', 'asset_type': 'cash_equity'}, {'symbol': 'LEN', 'asset_type': 'cash_equity'},
              {'symbol': 'L', 'asset_type': 'cash_equity'}, {'symbol': 'BLDR', 'asset_type': 'cash_equity'},
              {'symbol': 'LKQ', 'asset_type': 'cash_equity'}, {'symbol': 'ECL', 'asset_type': 'cash_equity'},
              {'symbol': 'CVX', 'asset_type': 'cash_equity'}, {'symbol': 'EBAY', 'asset_type': 'cash_equity'},
              {'symbol': 'FITB', 'asset_type': 'cash_equity'}, {'symbol': 'BLK', 'asset_type': 'cash_equity'},
              {'symbol': 'LUV', 'asset_type': 'cash_equity'}, {'symbol': 'MA', 'asset_type': 'cash_equity'},
              {'symbol': 'MAA', 'asset_type': 'cash_equity'}, {'symbol': 'FFIV', 'asset_type': 'cash_equity'},
              {'symbol': 'MAS', 'asset_type': 'cash_equity'}, {'symbol': 'MCK', 'asset_type': 'cash_equity'},
              {'symbol': 'MCO', 'asset_type': 'cash_equity'}, {'symbol': 'CTSH', 'asset_type': 'cash_equity'},
              {'symbol': 'CTLT', 'asset_type': 'cash_equity'}, {'symbol': 'MHK', 'asset_type': 'cash_equity'},
              {'symbol': 'CTAS', 'asset_type': 'cash_equity'}, {'symbol': 'CSX', 'asset_type': 'cash_equity'},
              {'symbol': 'BIIB', 'asset_type': 'cash_equity'}, {'symbol': 'MLM', 'asset_type': 'cash_equity'},
              {'symbol': 'MMM', 'asset_type': 'cash_equity'}, {'symbol': 'FCX', 'asset_type': 'cash_equity'},
              {'symbol': 'MPC', 'asset_type': 'cash_equity'}, {'symbol': 'FRT', 'asset_type': 'cash_equity'},
              {'symbol': 'LH', 'asset_type': 'cash_equity'}, {'symbol': 'LHX', 'asset_type': 'cash_equity'},
              {'symbol': 'MPWR', 'asset_type': 'cash_equity'}, {'symbol': 'CSGP', 'asset_type': 'cash_equity'},
              {'symbol': 'MRNA', 'asset_type': 'cash_equity'}, {'symbol': 'MRO', 'asset_type': 'cash_equity'},
              {'symbol': 'CSCO', 'asset_type': 'cash_equity'}, {'symbol': 'ZTS', 'asset_type': 'cash_equity'},
              {'symbol': 'MS', 'asset_type': 'cash_equity'}, {'symbol': 'MSI', 'asset_type': 'cash_equity'},
              {'symbol': 'BG', 'asset_type': 'cash_equity'}, {'symbol': 'LIN', 'asset_type': 'cash_equity'},
              {'symbol': 'MKTX', 'asset_type': 'cash_equity'}, {'symbol': 'AEE', 'asset_type': 'cash_equity'},
              {'symbol': 'ARE', 'asset_type': 'cash_equity'}, {'symbol': 'MGM', 'asset_type': 'cash_equity'},
              {'symbol': 'MTCH', 'asset_type': 'cash_equity'}, {'symbol': 'MTD', 'asset_type': 'cash_equity'},
              {'symbol': 'LLY', 'asset_type': 'cash_equity'}, {'symbol': 'ADSK', 'asset_type': 'cash_equity'},
              {'symbol': 'MU', 'asset_type': 'cash_equity'}, {'symbol': 'MOS', 'asset_type': 'cash_equity'},
              {'symbol': 'FOXA', 'asset_type': 'cash_equity'}, {'symbol': 'FOX', 'asset_type': 'cash_equity'},
              {'symbol': 'CLX', 'asset_type': 'cash_equity'}, {'symbol': 'LNT', 'asset_type': 'cash_equity'},
              {'symbol': 'MRK', 'asset_type': 'cash_equity'}, {'symbol': 'BDX', 'asset_type': 'cash_equity'},
              {'symbol': 'ADP', 'asset_type': 'cash_equity'}, {'symbol': 'FANG', 'asset_type': 'cash_equity'},
              {'symbol': 'NEE', 'asset_type': 'cash_equity'}, {'symbol': 'BKR', 'asset_type': 'cash_equity'},
              {'symbol': 'NEM', 'asset_type': 'cash_equity'}, {'symbol': 'BKNG', 'asset_type': 'cash_equity'},
              {'symbol': 'AAPL', 'asset_type': 'cash_equity'}, {'symbol': 'NCLH', 'asset_type': 'cash_equity'},
              {'symbol': 'NFLX', 'asset_type': 'cash_equity'}, {'symbol': 'LULU', 'asset_type': 'cash_equity'},
              {'symbol': 'LW', 'asset_type': 'cash_equity'}, {'symbol': 'NKE', 'asset_type': 'cash_equity'},
              {'symbol': 'NOC', 'asset_type': 'cash_equity'}, {'symbol': 'MAR', 'asset_type': 'cash_equity'},
              {'symbol': 'NOW', 'asset_type': 'cash_equity'}, {'symbol': 'MCHP', 'asset_type': 'cash_equity'},
              {'symbol': 'NRG', 'asset_type': 'cash_equity'}, {'symbol': 'MDLZ', 'asset_type': 'cash_equity'},
              {'symbol': 'MDT', 'asset_type': 'cash_equity'}, {'symbol': 'NSC', 'asset_type': 'cash_equity'},
              {'symbol': 'BF.B', 'asset_type': 'cash_equity'}, {'symbol': 'META', 'asset_type': 'cash_equity'},
              {'symbol': 'NUE', 'asset_type': 'cash_equity'}, {'symbol': 'FIS', 'asset_type': 'cash_equity'},
              {'symbol': 'NVDA', 'asset_type': 'cash_equity'}, {'symbol': 'NVR', 'asset_type': 'cash_equity'},
              {'symbol': 'CPT', 'asset_type': 'cash_equity'}, {'symbol': 'MKC', 'asset_type': 'cash_equity'},
              {'symbol': 'NXPI', 'asset_type': 'cash_equity'}, {'symbol': 'CPRT', 'asset_type': 'cash_equity'},
              {'symbol': 'ABNB', 'asset_type': 'cash_equity'}, {'symbol': 'MMC', 'asset_type': 'cash_equity'},
              {'symbol': 'COR', 'asset_type': 'cash_equity'}, {'symbol': 'MNST', 'asset_type': 'cash_equity'},
              {'symbol': 'AMD', 'asset_type': 'cash_equity'}, {'symbol': 'MOH', 'asset_type': 'cash_equity'},
              {'symbol': 'COP', 'asset_type': 'cash_equity'}, {'symbol': 'ODFL', 'asset_type': 'cash_equity'},
              {'symbol': 'FICO', 'asset_type': 'cash_equity'}, {'symbol': 'FI', 'asset_type': 'cash_equity'},
              {'symbol': 'BEN', 'asset_type': 'cash_equity'}, {'symbol': 'OKE', 'asset_type': 'cash_equity'},
              {'symbol': 'COF', 'asset_type': 'cash_equity'}, {'symbol': 'BA', 'asset_type': 'cash_equity'},
              {'symbol': 'FE', 'asset_type': 'cash_equity'}, {'symbol': 'FDX', 'asset_type': 'cash_equity'},
              {'symbol': 'FDS', 'asset_type': 'cash_equity'}, {'symbol': 'EXPE', 'asset_type': 'cash_equity'},
              {'symbol': 'EXPD', 'asset_type': 'cash_equity'}, {'symbol': 'NI', 'asset_type': 'cash_equity'},
              {'symbol': 'PAYC', 'asset_type': 'cash_equity'}, {'symbol': 'PCAR', 'asset_type': 'cash_equity'},
              {'symbol': 'DIS', 'asset_type': 'cash_equity'}, {'symbol': 'AVB', 'asset_type': 'cash_equity'},
              {'symbol': 'PEG', 'asset_type': 'cash_equity'}, {'symbol': 'PFE', 'asset_type': 'cash_equity'},
              {'symbol': 'PG', 'asset_type': 'cash_equity'}, {'symbol': 'EW', 'asset_type': 'cash_equity'},
              {'symbol': 'PH', 'asset_type': 'cash_equity'}, {'symbol': 'NTAP', 'asset_type': 'cash_equity'},
              {'symbol': 'PHM', 'asset_type': 'cash_equity'}, {'symbol': 'GL', 'asset_type': 'cash_equity'},
              {'symbol': 'DHR', 'asset_type': 'cash_equity'}, {'symbol': 'DHI', 'asset_type': 'cash_equity'},
              {'symbol': 'AVGO', 'asset_type': 'cash_equity'}, {'symbol': 'AWK', 'asset_type': 'cash_equity'},
              {'symbol': 'NWS', 'asset_type': 'cash_equity'}, {'symbol': 'NWSA', 'asset_type': 'cash_equity'},
              {'symbol': 'APTV', 'asset_type': 'cash_equity'}, {'symbol': 'PM', 'asset_type': 'cash_equity'},
              {'symbol': 'ATO', 'asset_type': 'cash_equity'}, {'symbol': 'BK', 'asset_type': 'cash_equity'},
              {'symbol': 'GRMN', 'asset_type': 'cash_equity'}, {'symbol': 'PNC', 'asset_type': 'cash_equity'},
              {'symbol': 'HUBB', 'asset_type': 'cash_equity'}, {'symbol': 'PNR', 'asset_type': 'cash_equity'},
              {'symbol': 'PODD', 'asset_type': 'cash_equity'}, {'symbol': 'PPG', 'asset_type': 'cash_equity'},
              {'symbol': 'HCA', 'asset_type': 'cash_equity'}, {'symbol': 'HPQ', 'asset_type': 'cash_equity'},
              {'symbol': 'ORCL', 'asset_type': 'cash_equity'}, {'symbol': 'OTIS', 'asset_type': 'cash_equity'},
              {'symbol': 'EXR', 'asset_type': 'cash_equity'}, {'symbol': 'CNC', 'asset_type': 'cash_equity'},
              {'symbol': 'AMAT', 'asset_type': 'cash_equity'}, {'symbol': 'PSA', 'asset_type': 'cash_equity'},
              {'symbol': 'PCG', 'asset_type': 'cash_equity'}, {'symbol': 'PSX', 'asset_type': 'cash_equity'},
              {'symbol': 'PFG', 'asset_type': 'cash_equity'}, {'symbol': 'AVY', 'asset_type': 'cash_equity'},
              {'symbol': 'EVRG', 'asset_type': 'cash_equity'}, {'symbol': 'PGR', 'asset_type': 'cash_equity'},
              {'symbol': 'IBM', 'asset_type': 'cash_equity'}, {'symbol': 'HON', 'asset_type': 'cash_equity'},
              {'symbol': 'PWR', 'asset_type': 'cash_equity'}, {'symbol': 'CMG', 'asset_type': 'cash_equity'},
              {'symbol': 'ADM', 'asset_type': 'cash_equity'}, {'symbol': 'PKG', 'asset_type': 'cash_equity'},
              {'symbol': 'CME', 'asset_type': 'cash_equity'}, {'symbol': 'QCOM', 'asset_type': 'cash_equity'},
              {'symbol': 'HLT', 'asset_type': 'cash_equity'}, {'symbol': 'POOL', 'asset_type': 'cash_equity'},
              {'symbol': 'PPL', 'asset_type': 'cash_equity'}, {'symbol': 'ETSY', 'asset_type': 'cash_equity'},
              {'symbol': 'ETR', 'asset_type': 'cash_equity'}, {'symbol': 'ETN', 'asset_type': 'cash_equity'},
              {'symbol': 'ESS', 'asset_type': 'cash_equity'}, {'symbol': 'QRVO', 'asset_type': 'cash_equity'},
              {'symbol': 'ES', 'asset_type': 'cash_equity'}, {'symbol': 'REG', 'asset_type': 'cash_equity'},
              {'symbol': 'RF', 'asset_type': 'cash_equity'}, {'symbol': 'EQT', 'asset_type': 'cash_equity'},
              {'symbol': 'EQR', 'asset_type': 'cash_equity'}, {'symbol': 'CZR', 'asset_type': 'cash_equity'},
              {'symbol': 'EQIX', 'asset_type': 'cash_equity'}, {'symbol': 'EOG', 'asset_type': 'cash_equity'},
              {'symbol': 'ADI', 'asset_type': 'cash_equity'}, {'symbol': 'PYPL', 'asset_type': 'cash_equity'},
              {'symbol': 'RJF', 'asset_type': 'cash_equity'}, {'symbol': 'RMD', 'asset_type': 'cash_equity'},
              {'symbol': 'CTVA', 'asset_type': 'cash_equity'}, {'symbol': 'K', 'asset_type': 'cash_equity'},
              {'symbol': 'CL', 'asset_type': 'cash_equity'}, {'symbol': 'ROK', 'asset_type': 'cash_equity'},
              {'symbol': 'ROP', 'asset_type': 'cash_equity'}, {'symbol': 'ROST', 'asset_type': 'cash_equity'},
              {'symbol': 'EPAM', 'asset_type': 'cash_equity'}, {'symbol': 'RSG', 'asset_type': 'cash_equity'},
              {'symbol': 'BBY', 'asset_type': 'cash_equity'}, {'symbol': 'EMN', 'asset_type': 'cash_equity'},
              {'symbol': 'LDOS', 'asset_type': 'cash_equity'}, {'symbol': 'ENPH', 'asset_type': 'cash_equity'},
              {'symbol': 'BBWI', 'asset_type': 'cash_equity'}, {'symbol': 'EL', 'asset_type': 'cash_equity'},
              {'symbol': 'EFX', 'asset_type': 'cash_equity'}, {'symbol': 'HII', 'asset_type': 'cash_equity'},
              {'symbol': 'HIG', 'asset_type': 'cash_equity'}, {'symbol': 'RL', 'asset_type': 'cash_equity'},
              {'symbol': 'SBAC', 'asset_type': 'cash_equity'}, {'symbol': 'LVS', 'asset_type': 'cash_equity'},
              {'symbol': 'ROL', 'asset_type': 'cash_equity'}, {'symbol': 'HD', 'asset_type': 'cash_equity'},
              {'symbol': 'BMY', 'asset_type': 'cash_equity'}, {'symbol': 'DXCM', 'asset_type': 'cash_equity'},
              {'symbol': 'DVN', 'asset_type': 'cash_equity'}, {'symbol': 'DVA', 'asset_type': 'cash_equity'},
              {'symbol': 'CRWD', 'asset_type': 'cash_equity'}, {'symbol': 'MO', 'asset_type': 'cash_equity'},
              {'symbol': 'DOW', 'asset_type': 'cash_equity'}, {'symbol': 'DOV', 'asset_type': 'cash_equity'},
              {'symbol': 'SJM', 'asset_type': 'cash_equity'}, {'symbol': 'ELV', 'asset_type': 'cash_equity'},
              {'symbol': 'SBUX', 'asset_type': 'cash_equity'}, {'symbol': 'DLTR', 'asset_type': 'cash_equity'},
              {'symbol': 'SHW', 'asset_type': 'cash_equity'}, {'symbol': 'APH', 'asset_type': 'cash_equity'},
              {'symbol': 'DGX', 'asset_type': 'cash_equity'}, {'symbol': 'EIX', 'asset_type': 'cash_equity'},
              {'symbol': 'SO', 'asset_type': 'cash_equity'}, {'symbol': 'CHRW', 'asset_type': 'cash_equity'},
              {'symbol': 'DG', 'asset_type': 'cash_equity'}, {'symbol': 'APD', 'asset_type': 'cash_equity'},
              {'symbol': 'DFS', 'asset_type': 'cash_equity'}, {'symbol': 'NTRS', 'asset_type': 'cash_equity'},
              {'symbol': 'SMCI', 'asset_type': 'cash_equity'}, {'symbol': 'BIO', 'asset_type': 'cash_equity'},
              {'symbol': 'BAX', 'asset_type': 'cash_equity'}, {'symbol': 'DECK', 'asset_type': 'cash_equity'},
              {'symbol': 'CFG', 'asset_type': 'cash_equity'}, {'symbol': 'DE', 'asset_type': 'cash_equity'},
              {'symbol': 'APA', 'asset_type': 'cash_equity'}, {'symbol': 'STT', 'asset_type': 'cash_equity'},
              {'symbol': 'HAS', 'asset_type': 'cash_equity'}, {'symbol': 'PANW', 'asset_type': 'cash_equity'},
              {'symbol': 'SWKS', 'asset_type': 'cash_equity'}, {'symbol': 'DAL', 'asset_type': 'cash_equity'},
              {'symbol': 'STZ', 'asset_type': 'cash_equity'}, {'symbol': 'HAL', 'asset_type': 'cash_equity'},
              {'symbol': 'CVS', 'asset_type': 'cash_equity'}, {'symbol': 'SRE', 'asset_type': 'cash_equity'},
              {'symbol': 'CTRA', 'asset_type': 'cash_equity'}, {'symbol': 'PEP', 'asset_type': 'cash_equity'},
              {'symbol': 'AOS', 'asset_type': 'cash_equity'}, {'symbol': 'CEG', 'asset_type': 'cash_equity'},
              {'symbol': 'SW', 'asset_type': 'cash_equity'}, {'symbol': 'CRM', 'asset_type': 'cash_equity'},
              {'symbol': 'CRL', 'asset_type': 'cash_equity'}, {'symbol': 'T', 'asset_type': 'cash_equity'},
              {'symbol': 'TDG', 'asset_type': 'cash_equity'}, {'symbol': 'PLD', 'asset_type': 'cash_equity'},
              {'symbol': 'CPB', 'asset_type': 'cash_equity'}, {'symbol': 'CPAY', 'asset_type': 'cash_equity'},
              {'symbol': 'COST', 'asset_type': 'cash_equity'}, {'symbol': 'AON', 'asset_type': 'cash_equity'},
              {'symbol': 'COO', 'asset_type': 'cash_equity'}, {'symbol': 'TFC', 'asset_type': 'cash_equity'},
              {'symbol': 'CNP', 'asset_type': 'cash_equity'}, {'symbol': 'BALL', 'asset_type': 'cash_equity'},
              {'symbol': 'EA', 'asset_type': 'cash_equity'}, {'symbol': 'SYK', 'asset_type': 'cash_equity'},
              {'symbol': 'SYY', 'asset_type': 'cash_equity'}, {'symbol': 'TJX', 'asset_type': 'cash_equity'},
              {'symbol': 'TMO', 'asset_type': 'cash_equity'}, {'symbol': 'CMS', 'asset_type': 'cash_equity'},
              {'symbol': 'TGT', 'asset_type': 'cash_equity'}, {'symbol': 'CMCSA', 'asset_type': 'cash_equity'},
              {'symbol': 'PTC', 'asset_type': 'cash_equity'}, {'symbol': 'ANSS', 'asset_type': 'cash_equity'},
              {'symbol': 'CINF', 'asset_type': 'cash_equity'}, {'symbol': 'AMZN', 'asset_type': 'cash_equity'},
              {'symbol': 'ACN', 'asset_type': 'cash_equity'}, {'symbol': 'TPR', 'asset_type': 'cash_equity'},
              {'symbol': 'TRGP', 'asset_type': 'cash_equity'}, {'symbol': 'AMT', 'asset_type': 'cash_equity'},
              {'symbol': 'TROW', 'asset_type': 'cash_equity'}, {'symbol': 'DTE', 'asset_type': 'cash_equity'},
              {'symbol': 'ALL', 'asset_type': 'cash_equity'}, {'symbol': 'CI', 'asset_type': 'cash_equity'},
              {'symbol': 'CHTR', 'asset_type': 'cash_equity'}, {'symbol': 'TRV', 'asset_type': 'cash_equity'},
              {'symbol': 'TSLA', 'asset_type': 'cash_equity'}, {'symbol': 'TRMB', 'asset_type': 'cash_equity'},
              {'symbol': 'AMGN', 'asset_type': 'cash_equity'}, {'symbol': 'AME', 'asset_type': 'cash_equity'},
              {'symbol': 'AMCR', 'asset_type': 'cash_equity'}, {'symbol': 'VST', 'asset_type': 'cash_equity'},
              {'symbol': 'CF', 'asset_type': 'cash_equity'}, {'symbol': 'TT', 'asset_type': 'cash_equity'},
              {'symbol': 'TXT', 'asset_type': 'cash_equity'}, {'symbol': 'UAL', 'asset_type': 'cash_equity'},
              {'symbol': 'UBER', 'asset_type': 'cash_equity'}, {'symbol': 'ALGN', 'asset_type': 'cash_equity'},
              {'symbol': 'BAC', 'asset_type': 'cash_equity'}, {'symbol': 'TXN', 'asset_type': 'cash_equity'},
              {'symbol': 'UDR', 'asset_type': 'cash_equity'}, {'symbol': 'ALB', 'asset_type': 'cash_equity'},
              {'symbol': 'AFL', 'asset_type': 'cash_equity'}, {'symbol': 'DRI', 'asset_type': 'cash_equity'},
              {'symbol': 'TYL', 'asset_type': 'cash_equity'}, {'symbol': 'AEP', 'asset_type': 'cash_equity'},
              {'symbol': 'UNH', 'asset_type': 'cash_equity'}, {'symbol': 'UPS', 'asset_type': 'cash_equity'},
              {'symbol': 'CHD', 'asset_type': 'cash_equity'}, {'symbol': 'UHS', 'asset_type': 'cash_equity'},
              {'symbol': 'CDW', 'asset_type': 'cash_equity'}, {'symbol': 'UNP', 'asset_type': 'cash_equity'},
              {'symbol': 'DPZ', 'asset_type': 'cash_equity'}, {'symbol': 'AIG', 'asset_type': 'cash_equity'},
              {'symbol': 'CDNS', 'asset_type': 'cash_equity'}, {'symbol': 'USB', 'asset_type': 'cash_equity'},
              {'symbol': 'ADBE', 'asset_type': 'cash_equity'}, {'symbol': 'ANET', 'asset_type': 'cash_equity'},
              {'symbol': 'V', 'asset_type': 'cash_equity'}, {'symbol': 'VICI', 'asset_type': 'cash_equity'},
              {'symbol': 'AZO', 'asset_type': 'cash_equity'}, {'symbol': 'AES', 'asset_type': 'cash_equity'},
              {'symbol': 'VLO', 'asset_type': 'cash_equity'}, {'symbol': 'VLTO', 'asset_type': 'cash_equity'},
              {'symbol': 'VMC', 'asset_type': 'cash_equity'}, {'symbol': 'GPN', 'asset_type': 'cash_equity'},
              {'symbol': 'GPC', 'asset_type': 'cash_equity'}, {'symbol': 'SNPS', 'asset_type': 'cash_equity'},
              {'symbol': 'ABBV', 'asset_type': 'cash_equity'}, {'symbol': 'GOOGL', 'asset_type': 'cash_equity'},
              {'symbol': 'DOC', 'asset_type': 'cash_equity'}, {'symbol': 'VRSN', 'asset_type': 'cash_equity'},
              {'symbol': 'VTR', 'asset_type': 'cash_equity'}, {'symbol': 'CE', 'asset_type': 'cash_equity'},
              {'symbol': 'WAB', 'asset_type': 'cash_equity'}, {'symbol': 'WAT', 'asset_type': 'cash_equity'},
              {'symbol': 'CCL', 'asset_type': 'cash_equity'}, {'symbol': 'DLR', 'asset_type': 'cash_equity'},
              {'symbol': 'CCI', 'asset_type': 'cash_equity'}, {'symbol': 'STE', 'asset_type': 'cash_equity'},
              {'symbol': 'STLD', 'asset_type': 'cash_equity'}, {'symbol': 'WEC', 'asset_type': 'cash_equity'},
              {'symbol': 'A', 'asset_type': 'cash_equity'}, {'symbol': 'STX', 'asset_type': 'cash_equity'},
              {'symbol': 'CBRE', 'asset_type': 'cash_equity'}, {'symbol': 'CBOE', 'asset_type': 'cash_equity'},
              {'symbol': 'WELL', 'asset_type': 'cash_equity'}, {'symbol': 'CB', 'asset_type': 'cash_equity'},
              {'symbol': 'RTX', 'asset_type': 'cash_equity'}, {'symbol': 'CARR', 'asset_type': 'cash_equity'},
              {'symbol': 'SWK', 'asset_type': 'cash_equity'}, {'symbol': 'WM', 'asset_type': 'cash_equity'},
              {'symbol': 'WMB', 'asset_type': 'cash_equity'}, {'symbol': 'WRB', 'asset_type': 'cash_equity'},
              {'symbol': 'C', 'asset_type': 'cash_equity'}, {'symbol': 'GNRC', 'asset_type': 'cash_equity'},
              {'symbol': 'AAL', 'asset_type': 'cash_equity'}, {'symbol': 'BXP', 'asset_type': 'cash_equity'},
              {'symbol': 'BX', 'asset_type': 'cash_equity'}, {'symbol': 'WMT', 'asset_type': 'cash_equity'},
              {'symbol': 'WST', 'asset_type': 'cash_equity'}, {'symbol': 'TDY', 'asset_type': 'cash_equity'},
              {'symbol': 'TEL', 'asset_type': 'cash_equity'}, {'symbol': 'TFX', 'asset_type': 'cash_equity'},
              {'symbol': 'WTW', 'asset_type': 'cash_equity'}, {'symbol': 'CAT', 'asset_type': 'cash_equity'},
              {'symbol': 'WY', 'asset_type': 'cash_equity'}, {'symbol': 'GS', 'asset_type': 'cash_equity'},
              {'symbol': 'XOM', 'asset_type': 'cash_equity'}, {'symbol': 'BSX', 'asset_type': 'cash_equity'},
              {'symbol': 'GWW', 'asset_type': 'cash_equity'}, {'symbol': 'JKHY', 'asset_type': 'cash_equity'},
              {'symbol': 'CAG', 'asset_type': 'cash_equity'}, {'symbol': 'HBAN', 'asset_type': 'cash_equity'},
              {'symbol': 'GOOG', 'asset_type': 'cash_equity'}, {'symbol': 'HES', 'asset_type': 'cash_equity'},
              {'symbol': 'GEHC', 'asset_type': 'cash_equity'}, {'symbol': 'AXP', 'asset_type': 'cash_equity'},
              {'symbol': 'FAST', 'asset_type': 'cash_equity'}, {'symbol': 'XYL', 'asset_type': 'cash_equity'},
              {'symbol': 'CAH', 'asset_type': 'cash_equity'}, {'symbol': 'F', 'asset_type': 'cash_equity'},
              {'symbol': 'KO', 'asset_type': 'cash_equity'}, {'symbol': 'TMUS', 'asset_type': 'cash_equity'},
              {'symbol': 'INTU', 'asset_type': 'cash_equity'}, {'symbol': 'ACGL', 'asset_type': 'cash_equity'},
              {'symbol': 'PARA', 'asset_type': 'cash_equity'}, {'symbol': 'BRK.B', 'asset_type': 'cash_equity'},
              {'symbol': 'ALLE', 'asset_type': 'cash_equity'}, {'symbol': 'TTWO', 'asset_type': 'cash_equity'},
              {'symbol': 'VRTX', 'asset_type': 'cash_equity'}]

# https://www.ishares.com/us/products/308574/ishares-esg-msci-usa-leaders-etf-fund
# The iShares ESG MSCI USA Leaders ETF (the “Fund”) seeks to track the investment results of an index composed of U.S. large and mid-capitalization stocks of companies with high environmental, social, and governance performance relative to their sector peers as determined by the index provider.
SP500_HIGH_ESG = [
    {'symbol': 'MSFT', 'asset_type': 'cash_equity'},
    {'symbol': 'NVDA', 'asset_type': 'cash_equity'},
    {'symbol': 'GOOGL', 'asset_type': 'cash_equity'},
    {'symbol': 'GOOG', 'asset_type': 'cash_equity'},
    {'symbol': 'LLY', 'asset_type': 'cash_equity'},
    {'symbol': 'TSLA', 'asset_type': 'cash_equity'},
    {'symbol': 'V', 'asset_type': 'cash_equity'},
    {'symbol': 'PG', 'asset_type': 'cash_equity'},
    {'symbol': 'MA', 'asset_type': 'cash_equity'},
    {'symbol': 'JNJ', 'asset_type': 'cash_equity'},
    {'symbol': 'HD', 'asset_type': 'cash_equity'},
    {'symbol': 'MRK', 'asset_type': 'cash_equity'},
    {'symbol': 'KO', 'asset_type': 'cash_equity'},
    {'symbol': 'CRM', 'asset_type': 'cash_equity'},
    {'symbol': 'AMD', 'asset_type': 'cash_equity'},
    {'symbol': 'PEP', 'asset_type': 'cash_equity'},
    {'symbol': 'ADBE', 'asset_type': 'cash_equity'},
    {'symbol': 'LIN', 'asset_type': 'cash_equity'},
    {'symbol': 'MCD', 'asset_type': 'cash_equity'},
    {'symbol': 'ACN', 'asset_type': 'cash_equity'},
    {'symbol': 'GE', 'asset_type': 'cash_equity'},
    {'symbol': 'IBM', 'asset_type': 'cash_equity'},
    {'symbol': 'NOW', 'asset_type': 'cash_equity'},
    {'symbol': 'VZ', 'asset_type': 'cash_equity'},
    {'symbol': 'TXN', 'asset_type': 'cash_equity'},
    {'symbol': 'DHR', 'asset_type': 'cash_equity'},
    {'symbol': 'AMGN', 'asset_type': 'cash_equity'},
    {'symbol': 'CAT', 'asset_type': 'cash_equity'},
    {'symbol': 'INTU', 'asset_type': 'cash_equity'},
    {'symbol': 'DIS', 'asset_type': 'cash_equity'},
    {'symbol': 'SPGI', 'asset_type': 'cash_equity'},
    {'symbol': 'AMAT', 'asset_type': 'cash_equity'},
    {'symbol': 'CMCSA', 'asset_type': 'cash_equity'},
    {'symbol': 'AXP', 'asset_type': 'cash_equity'},
    {'symbol': 'PGR', 'asset_type': 'cash_equity'},
    {'symbol': 'UNP', 'asset_type': 'cash_equity'},
    {'symbol': 'LOW', 'asset_type': 'cash_equity'},
    {'symbol': 'BLK', 'asset_type': 'cash_equity'},
    {'symbol': 'BKNG', 'asset_type': 'cash_equity'},
    {'symbol': 'TJX', 'asset_type': 'cash_equity'},
    {'symbol': 'ETN', 'asset_type': 'cash_equity'},
    {'symbol': 'ELV', 'asset_type': 'cash_equity'},
    {'symbol': 'MS', 'asset_type': 'cash_equity'},
    {'symbol': 'PLD', 'asset_type': 'cash_equity'},
    {'symbol': 'ADP', 'asset_type': 'cash_equity'},
    {'symbol': 'MMC', 'asset_type': 'cash_equity'},
    {'symbol': 'PANW', 'asset_type': 'cash_equity'},
    {'symbol': 'AMT', 'asset_type': 'cash_equity'},
    {'symbol': 'DE', 'asset_type': 'cash_equity'},
    {'symbol': 'NKE', 'asset_type': 'cash_equity'},
    {'symbol': 'GILD', 'asset_type': 'cash_equity'},
    {'symbol': 'FI', 'asset_type': 'cash_equity'},
    {'symbol': 'CI', 'asset_type': 'cash_equity'},
    {'symbol': 'LRCX', 'asset_type': 'cash_equity'},
    {'symbol': 'BMY', 'asset_type': 'cash_equity'},
    {'symbol': 'SCHW', 'asset_type': 'cash_equity'},
    {'symbol': 'MELI', 'asset_type': 'cash_equity'},
    {'symbol': 'UPS', 'asset_type': 'cash_equity'},
    {'symbol': 'INTC', 'asset_type': 'cash_equity'},
    {'symbol': 'ICE', 'asset_type': 'cash_equity'},
    {'symbol': 'ZTS', 'asset_type': 'cash_equity'},
    {'symbol': 'TT', 'asset_type': 'cash_equity'},
    {'symbol': 'EQIX', 'asset_type': 'cash_equity'},
    {'symbol': 'MCO', 'asset_type': 'cash_equity'},
    {'symbol': 'CL', 'asset_type': 'cash_equity'},
    {'symbol': 'HCA', 'asset_type': 'cash_equity'},
    {'symbol': 'SNPS', 'asset_type': 'cash_equity'},
    {'symbol': 'PYPL', 'asset_type': 'cash_equity'},
    {'symbol': 'ITW', 'asset_type': 'cash_equity'},
    {'symbol': 'WELL', 'asset_type': 'cash_equity'},
    {'symbol': 'CTAS', 'asset_type': 'cash_equity'},
    {'symbol': 'CDNS', 'asset_type': 'cash_equity'},
    {'symbol': 'MMM', 'asset_type': 'cash_equity'},
    {'symbol': 'PNC', 'asset_type': 'cash_equity'},
    {'symbol': 'USB', 'asset_type': 'cash_equity'},
    {'symbol': 'TGT', 'asset_type': 'cash_equity'},
    {'symbol': 'XTSLA', 'asset_type': 'cash'},
    {'symbol': 'CSX', 'asset_type': 'cash_equity'},
    {'symbol': 'ORLY', 'asset_type': 'cash_equity'},
    {'symbol': 'CARR', 'asset_type': 'cash_equity'},
    {'symbol': 'ECL', 'asset_type': 'cash_equity'},
    {'symbol': 'APD', 'asset_type': 'cash_equity'},
    {'symbol': 'MRVL', 'asset_type': 'cash_equity'},
    {'symbol': 'CRH', 'asset_type': 'cash_equity'},
    {'symbol': 'NEM', 'asset_type': 'cash_equity'},
    {'symbol': 'SLB', 'asset_type': 'cash_equity'},
    {'symbol': 'NXPI', 'asset_type': 'cash_equity'},
    {'symbol': 'AFL', 'asset_type': 'cash_equity'},
    {'symbol': 'COF', 'asset_type': 'cash_equity'},
    {'symbol': 'MPC', 'asset_type': 'cash_equity'},
    {'symbol': 'ADSK', 'asset_type': 'cash_equity'},
    {'symbol': 'DHI', 'asset_type': 'cash_equity'},
    {'symbol': 'TFC', 'asset_type': 'cash_equity'},
    {'symbol': 'HLT', 'asset_type': 'cash_equity'},
    {'symbol': 'WMB', 'asset_type': 'cash_equity'},
    {'symbol': 'PSX', 'asset_type': 'cash_equity'},
    {'symbol': 'OKE', 'asset_type': 'cash_equity'},
    {'symbol': 'TRV', 'asset_type': 'cash_equity'},
    {'symbol': 'BK', 'asset_type': 'cash_equity'},
    {'symbol': 'WDAY', 'asset_type': 'cash_equity'},
    {'symbol': 'SRE', 'asset_type': 'cash_equity'},
    {'symbol': 'URI', 'asset_type': 'cash_equity'},
    {'symbol': 'AZO', 'asset_type': 'cash_equity'},
    {'symbol': 'DLR', 'asset_type': 'cash_equity'},
    {'symbol': 'ALL', 'asset_type': 'cash_equity'},
    {'symbol': 'JCI', 'asset_type': 'cash_equity'},
    {'symbol': 'CCI', 'asset_type': 'cash_equity'},
    {'symbol': 'FICO', 'asset_type': 'cash_equity'},
    {'symbol': 'KMB', 'asset_type': 'cash_equity'},
    {'symbol': 'FIS', 'asset_type': 'cash_equity'},
    {'symbol': 'AMP', 'asset_type': 'cash_equity'},
    {'symbol': 'GWW', 'asset_type': 'cash_equity'},
    {'symbol': 'IQV', 'asset_type': 'cash_equity'},
    {'symbol': 'VLO', 'asset_type': 'cash_equity'},
    {'symbol': 'PRU', 'asset_type': 'cash_equity'},
    {'symbol': 'PAYX', 'asset_type': 'cash_equity'},
    {'symbol': 'DASH', 'asset_type': 'cash_equity'},
    {'symbol': 'PWR', 'asset_type': 'cash_equity'},
    {'symbol': 'RCL', 'asset_type': 'cash_equity'},
    {'symbol': 'ACGL', 'asset_type': 'cash_equity'},
    {'symbol': 'CMI', 'asset_type': 'cash_equity'},
    {'symbol': 'IDXX', 'asset_type': 'cash_equity'},
    {'symbol': 'GIS', 'asset_type': 'cash_equity'},
    {'symbol': 'LNG', 'asset_type': 'cash_equity'},
    {'symbol': 'COR', 'asset_type': 'cash_equity'},
    {'symbol': 'A', 'asset_type': 'cash_equity'},
    {'symbol': 'KDP', 'asset_type': 'cash_equity'},
    {'symbol': 'EW', 'asset_type': 'cash_equity'},
    {'symbol': 'EXC', 'asset_type': 'cash_equity'},
    {'symbol': 'IT', 'asset_type': 'cash_equity'},
    {'symbol': 'FERG', 'asset_type': 'cash_equity'},
    {'symbol': 'GEHC', 'asset_type': 'cash_equity'},
    {'symbol': 'IR', 'asset_type': 'cash_equity'},
    {'symbol': 'KR', 'asset_type': 'cash_equity'},
    {'symbol': 'ODFL', 'asset_type': 'cash_equity'},
    {'symbol': 'HUM', 'asset_type': 'cash_equity'},
    {'symbol': 'CBRE', 'asset_type': 'cash_equity'},
    {'symbol': 'YUM', 'asset_type': 'cash_equity'},
    {'symbol': 'BKR', 'asset_type': 'cash_equity'},
    {'symbol': 'ED', 'asset_type': 'cash_equity'},
    {'symbol': 'DFS', 'asset_type': 'cash_equity'},
    {'symbol': 'EA', 'asset_type': 'cash_equity'},
    {'symbol': 'NUE', 'asset_type': 'cash_equity'},
    {'symbol': 'HIG', 'asset_type': 'cash_equity'},
    {'symbol': 'HPQ', 'asset_type': 'cash_equity'},
    {'symbol': 'IRM', 'asset_type': 'cash_equity'},
    {'symbol': 'MLM', 'asset_type': 'cash_equity'},
    {'symbol': 'EIX', 'asset_type': 'cash_equity'},
    {'symbol': 'XYL', 'asset_type': 'cash_equity'},
    {'symbol': 'NDAQ', 'asset_type': 'cash_equity'},
    {'symbol': 'TRGP', 'asset_type': 'cash_equity'},
    {'symbol': 'EBAY', 'asset_type': 'cash_equity'},
    {'symbol': 'CHTR', 'asset_type': 'cash_equity'},
    {'symbol': 'MTD', 'asset_type': 'cash_equity'},
    {'symbol': 'NVR', 'asset_type': 'cash_equity'},
    {'symbol': 'LULU', 'asset_type': 'cash_equity'},
    {'symbol': 'PHM', 'asset_type': 'cash_equity'},
    {'symbol': 'ROK', 'asset_type': 'cash_equity'},
    {'symbol': 'TSCO', 'asset_type': 'cash_equity'},
    {'symbol': 'PPG', 'asset_type': 'cash_equity'},
    {'symbol': 'WTW', 'asset_type': 'cash_equity'},
    {'symbol': 'BIIB', 'asset_type': 'cash_equity'},
    {'symbol': 'AWK', 'asset_type': 'cash_equity'},
    {'symbol': 'AXON', 'asset_type': 'cash_equity'},
    {'symbol': 'ANSS', 'asset_type': 'cash_equity'},
    {'symbol': 'DXCM', 'asset_type': 'cash_equity'},
    {'symbol': 'VLTO', 'asset_type': 'cash_equity'},
    {'symbol': 'FTV', 'asset_type': 'cash_equity'},
    {'symbol': 'KEYS', 'asset_type': 'cash_equity'},
    {'symbol': 'STT', 'asset_type': 'cash_equity'},
    {'symbol': 'IFF', 'asset_type': 'cash_equity'},
    {'symbol': 'DOV', 'asset_type': 'cash_equity'},
    {'symbol': 'HAL', 'asset_type': 'cash_equity'},
    {'symbol': 'TEAM', 'asset_type': 'cash_equity'},
    {'symbol': 'SBAC', 'asset_type': 'cash_equity'},
    {'symbol': 'HUBS', 'asset_type': 'cash_equity'},
    {'symbol': 'CHD', 'asset_type': 'cash_equity'},
    {'symbol': 'NTAP', 'asset_type': 'cash_equity'},
    {'symbol': 'TTWO', 'asset_type': 'cash_equity'},
    {'symbol': 'SW', 'asset_type': 'cash_equity'},
    {'symbol': 'BR', 'asset_type': 'cash_equity'},
    {'symbol': 'LYB', 'asset_type': 'cash_equity'},
    {'symbol': 'HPE', 'asset_type': 'cash_equity'},
    {'symbol': 'FSLR', 'asset_type': 'cash_equity'},
    {'symbol': 'RJF', 'asset_type': 'cash_equity'},
    {'symbol': 'WY', 'asset_type': 'cash_equity'},
    {'symbol': 'TROW', 'asset_type': 'cash_equity'},
    {'symbol': 'ES', 'asset_type': 'cash_equity'},
    {'symbol': 'STE', 'asset_type': 'cash_equity'},
    {'symbol': 'DECK', 'asset_type': 'cash_equity'},
    {'symbol': 'WST', 'asset_type': 'cash_equity'},
    {'symbol': 'K', 'asset_type': 'cash_equity'},
    {'symbol': 'COO', 'asset_type': 'cash_equity'},
    {'symbol': 'ZBH', 'asset_type': 'cash_equity'},
    {'symbol': 'WDC', 'asset_type': 'cash_equity'},
    {'symbol': 'CBOE', 'asset_type': 'cash_equity'},
    {'symbol': 'HBAN', 'asset_type': 'cash_equity'},
    {'symbol': 'PTC', 'asset_type': 'cash_equity'},
    {'symbol': 'RF', 'asset_type': 'cash_equity'},
    {'symbol': 'MKC', 'asset_type': 'cash_equity'},
    {'symbol': 'CMS', 'asset_type': 'cash_equity'},
    {'symbol': 'BALL', 'asset_type': 'cash_equity'},
    {'symbol': 'STX', 'asset_type': 'cash_equity'},
    {'symbol': 'ATO', 'asset_type': 'cash_equity'},
    {'symbol': 'DRI', 'asset_type': 'cash_equity'},
    {'symbol': 'MOH', 'asset_type': 'cash_equity'},
    {'symbol': 'CLX', 'asset_type': 'cash_equity'},
    {'symbol': 'EME', 'asset_type': 'cash_equity'},
    {'symbol': 'TRU', 'asset_type': 'cash_equity'},
    {'symbol': 'OMC', 'asset_type': 'cash_equity'},
    {'symbol': 'USD', 'asset_type': 'cash'},
    {'symbol': 'WAT', 'asset_type': 'cash_equity'},
    {'symbol': 'PFG', 'asset_type': 'cash_equity'},
    {'symbol': 'SYF', 'asset_type': 'cash_equity'},
    {'symbol': 'BBY', 'asset_type': 'cash_equity'},
    {'symbol': 'LII', 'asset_type': 'cash_equity'},
    {'symbol': 'ULTA', 'asset_type': 'cash_equity'},
    {'symbol': 'GPC', 'asset_type': 'cash_equity'},
    {'symbol': 'WSM', 'asset_type': 'cash_equity'},
    {'symbol': 'HOLX', 'asset_type': 'cash_equity'},
    {'symbol': 'CFG', 'asset_type': 'cash_equity'},
    {'symbol': 'APTV', 'asset_type': 'cash_equity'},
    {'symbol': 'NTRS', 'asset_type': 'cash_equity'},
    {'symbol': 'LH', 'asset_type': 'cash_equity'},
    {'symbol': 'AVTR', 'asset_type': 'cash_equity'},
    {'symbol': 'NRG', 'asset_type': 'cash_equity'},
    {'symbol': 'ALGN', 'asset_type': 'cash_equity'},
    {'symbol': 'STLD', 'asset_type': 'cash_equity'},
    {'symbol': 'FDS', 'asset_type': 'cash_equity'},
    {'symbol': 'EXPD', 'asset_type': 'cash_equity'},
    {'symbol': 'BURL', 'asset_type': 'cash_equity'},
    {'symbol': 'DGX', 'asset_type': 'cash_equity'},
    {'symbol': 'AVY', 'asset_type': 'cash_equity'},
    {'symbol': 'MANH', 'asset_type': 'cash_equity'},
    {'symbol': 'PODD', 'asset_type': 'cash_equity'},
    {'symbol': 'IP', 'asset_type': 'cash_equity'},
    {'symbol': 'LPLA', 'asset_type': 'cash_equity'},
    {'symbol': 'KEY', 'asset_type': 'cash_equity'},
    {'symbol': 'PNR', 'asset_type': 'cash_equity'},
    {'symbol': 'ENPH', 'asset_type': 'cash_equity'},
    {'symbol': 'IEX', 'asset_type': 'cash_equity'},
    {'symbol': 'ZS', 'asset_type': 'cash_equity'},
    {'symbol': 'DOC', 'asset_type': 'cash_equity'},
    {'symbol': 'CAG', 'asset_type': 'cash_equity'},
    {'symbol': 'NI', 'asset_type': 'cash_equity'},
    {'symbol': 'AKAM', 'asset_type': 'cash_equity'},
    {'symbol': 'GEN', 'asset_type': 'cash_equity'},
    {'symbol': 'OC', 'asset_type': 'cash_equity'},
    {'symbol': 'GGG', 'asset_type': 'cash_equity'},
    {'symbol': 'DPZ', 'asset_type': 'cash_equity'},
    {'symbol': 'TRMB', 'asset_type': 'cash_equity'},
    {'symbol': 'BG', 'asset_type': 'cash_equity'},
    {'symbol': 'JBHT', 'asset_type': 'cash_equity'},
    {'symbol': 'POOL', 'asset_type': 'cash_equity'},
    {'symbol': 'EQH', 'asset_type': 'cash_equity'},
    {'symbol': 'JNPR', 'asset_type': 'cash_equity'},
    {'symbol': 'SJM', 'asset_type': 'cash_equity'},
    {'symbol': 'CHRW', 'asset_type': 'cash_equity'},
    {'symbol': 'TECH', 'asset_type': 'cash_equity'},
    {'symbol': 'ALLE', 'asset_type': 'cash_equity'},
    {'symbol': 'BXP', 'asset_type': 'cash_equity'},
    {'symbol': 'NBIX', 'asset_type': 'cash_equity'},
    {'symbol': 'KMX', 'asset_type': 'cash_equity'},
    {'symbol': 'DOCU', 'asset_type': 'cash_equity'},
    {'symbol': 'IPG', 'asset_type': 'cash_equity'},
    {'symbol': 'TFX', 'asset_type': 'cash_equity'},
    {'symbol': 'FBIN', 'asset_type': 'cash_equity'},
    {'symbol': 'CTLT', 'asset_type': 'cash_equity'},
    {'symbol': 'LKQ', 'asset_type': 'cash_equity'},
    {'symbol': 'NLY', 'asset_type': 'cash_equity'},
    {'symbol': 'TWLO', 'asset_type': 'cash_equity'},
    {'symbol': 'SOLV', 'asset_type': 'cash_equity'},
    {'symbol': 'AIZ', 'asset_type': 'cash_equity'},
    {'symbol': 'CPB', 'asset_type': 'cash_equity'},
    {'symbol': 'WTRG', 'asset_type': 'cash_equity'},
    {'symbol': 'MKTX', 'asset_type': 'cash_equity'},
    {'symbol': 'HRL', 'asset_type': 'cash_equity'},
    {'symbol': 'CNH', 'asset_type': 'cash_equity'},
    {'symbol': 'LW', 'asset_type': 'cash_equity'},
    {'symbol': 'ALLY', 'asset_type': 'cash_equity'},
    {'symbol': 'DAY', 'asset_type': 'cash_equity'},
    {'symbol': 'FOXA', 'asset_type': 'cash_equity'},
    {'symbol': 'HSIC', 'asset_type': 'cash_equity'},
    {'symbol': 'TTC', 'asset_type': 'cash_equity'},
    {'symbol': 'DVA', 'asset_type': 'cash_equity'},
    {'symbol': 'RIVN', 'asset_type': 'cash_equity'},
    {'symbol': 'KNX', 'asset_type': 'cash_equity'},
    {'symbol': 'DINO', 'asset_type': 'cash_equity'},
    {'symbol': 'DAL', 'asset_type': 'cash_equity'},
    {'symbol': 'ACI', 'asset_type': 'cash_equity'},
    {'symbol': 'AZPN', 'asset_type': 'cash_equity'},
    {'symbol': 'WBA', 'asset_type': 'cash_equity'},
    {'symbol': 'BBWI', 'asset_type': 'cash_equity'},
    {'symbol': 'BEN', 'asset_type': 'cash_equity'},
    {'symbol': 'FOX', 'asset_type': 'cash_equity'},
    {'symbol': 'HBCFT', 'asset_type': 'cash'},
    {'symbol': 'ESZ4', 'asset_type': 'future_contract'}
]


SP500_LOW_ESG = []
high_symbols = [a["symbol"] for a  in SP500_HIGH_ESG]
for a in SP500_MAP:
    if a["symbol"] not in high_symbols:
        SP500_LOW_ESG.append(a)